version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      # target: development
    volumes:
      - ./server/src:/usr/src/app/src
      - /usr/src/app/node_modules # isolate container's node_modules from local node_modules (different OS versions)
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    # command: npm run test:unit
    command: npm run test:integration
    # command: npm run start:dev
    env_file:
      - .env
    # networks:
    #   - webnet
    depends_on:
      - db
    #   - webnet
  db:
    container_name: postgres
    image: postgres:13.1
    # networks:
    # - webnet
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
# networks:
#   webnet:
